name: Add PR Report Comment

on: 
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: false
      pr_author:
        description: 'Pull Request Author'
        required: false
  #pull_request:
    #types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-csv:    
    runs-on: ubuntu-latest
    if: github.event.pull_request != null && 
        github.event.pull_request.user.login == 'tthirmal'

    steps:
      - uses: actions/checkout@v4

      - name: Fetch PR files and reviewers and create CSV report
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_STATE: ${{ github.event.pull_request.state }}
          PR_MERGED: ${{ github.event.pull_request.merged }}
        run: |
          # Fetch changed files
          curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files > pr_files.json

          # Fetch requested reviewers
          curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/requested_reviewers > reviewers.json

          # Extract reviewers' usernames
          REVIEWERS=$(jq -r '.users[].login' reviewers.json | paste -sd "," -)

          # Create CSV file header including metadata columns
          echo "filename,status,additions,deletions,pr_author,pr_state,pr_merged,reviewers" > pr_report.csv

          # Append files info + metadata for each file
          jq -c '.[]' pr_files.json | while read -r file; do
            filename=$(echo "$file" | jq -r .filename)
            status=$(echo "$file" | jq -r .status)
            additions=$(echo "$file" | jq -r .additions)
            deletions=$(echo "$file" | jq -r .deletions)
            echo "\"$filename\",\"$status\",$additions,$deletions,\"$PR_AUTHOR\",\"$PR_STATE\",\"$PR_MERGED\",\"$REVIEWERS\"" \
              >> pr_report.csv
          done

      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-detailed-report
          path: pr_report.csv
