name: Add PR Report Comment

on: 
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-csv:
    if: github.event.pull_request.user.login == 'tthirmal'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create CSV of Changed Files
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.PR_TOKEN }}
        run: |
          curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files \
            > pr_files.json

          echo "filename,status,additions,deletions" > pr_files.csv
          jq -r '.[] | [.filename, .status, .additions, .deletions] | @csv' pr_files.json >> pr_files.csv

      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-files-report
          path: pr_files.csv
